# Generated by Django 5.2.8 on 2025-11-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='course_image',
            field=models.ImageField(blank=True, null=True, upload_to='couses/'),
        ),
        migrations.AlterField(
            model_name='trainermodel',
            name='trainer_photo',
            field=models.ImageField(blank=True, null=True, upload_to='triners/'),
        ),
    ]
