# Generated by Django 5.2.8 on 2025-11-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_alter_coursemodel_course_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='course_image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/'),
        ),
        migrations.AlterField(
            model_name='trainermodel',
            name='trainer_photo',
            field=models.ImageField(blank=True, null=True, upload_to='trainers/'),
        ),
    ]
