# Generated by Django 5.2.8 on 2025-11-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_alter_coursemodel_course_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainermodel',
            name='trainer_photo',
            field=models.ImageField(default='default.jpg', upload_to='trainers/'),
        ),
    ]
