# Generated by Django 5.2.8 on 2025-11-29 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_alter_trainermodel_trainer_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentmodel',
            options={'permissions': [('view_student_details', 'Can view student details')]},
        ),
    ]
